package io.bellabaxter;

import java.security.*;
import java.security.interfaces.ECPublicKey;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import javax.crypto.*;
import javax.crypto.spec.*;

/**
 * ECDH-P256-HKDF-SHA256-AES256GCM client-side decryption.
 *
 * <p>The Bella Baxter API encrypts secrets responses when the client sends an
 * {@code X-E2E-Public-Key} header.  This class generates the P-256 key pair
 * and decrypts the encrypted payload using Java's standard crypto libraries.
 *
 * <pre>{@code
 * E2EEncryption e2e = new E2EEncryption();
 * // Header to add: e2e.getPublicKeyBase64()
 * Map<String,String> secrets = e2e.decrypt(responseBodyBytes);
 * }</pre>
 */
public final class E2EEncryption {

    private static final String HKDF_INFO = "bella-e2ee-v1";

    /**
     * Fixed DER prefix for a P-256 SubjectPublicKeyInfo (SPKI / X.509):
     * SEQUENCE { AlgorithmIdentifier { ecPublicKey, secp256r1 } BIT STRING { unused=0 ... } }
     * The 65-byte uncompressed point (04 || X || Y) is appended after this header.
     */
    private static final byte[] SPKI_HEADER_P256 = hexDecode(
            "3059301306072a8648ce3d020106082a8648ce3d030107034200");

    private final PrivateKey privateKey;
    private final String     publicKeyBase64; // base64-encoded SubjectPublicKeyInfo (SPKI)

    /** Generate a new ephemeral P-256 key pair. */
    public E2EEncryption() {
        try {
            KeyPairGenerator kpg = KeyPairGenerator.getInstance("EC");
            kpg.initialize(new ECGenParameterSpec("secp256r1"), new SecureRandom());
            KeyPair kp = kpg.generateKeyPair();
            this.privateKey      = kp.getPrivate();
            this.publicKeyBase64 = Base64.getEncoder().encodeToString(kp.getPublic().getEncoded());
        } catch (GeneralSecurityException e) {
            throw new RuntimeException("E2EEncryption: key generation failed", e);
        }
    }

    /** Private constructor for an already-resolved key pair (used by {@link #fromPkcs8Pem}). */
    private E2EEncryption(PrivateKey privateKey, PublicKey publicKey) {
        this.privateKey      = privateKey;
        this.publicKeyBase64 = Base64.getEncoder().encodeToString(publicKey.getEncoded());
    }

    /**
     * Create an {@code E2EEncryption} from an existing PKCS#8 PEM private key.
     *
     * <p>Use this for ZKE (Zero-Knowledge Encryption) in M2M applications where the device
     * key is long-lived rather than ephemeral.  The PEM must be a P-256 (secp256r1) key
     * with the public key embedded in the PKCS#8 structure (the default for
     * {@code bella auth setup} and {@code openssl genpkey}).
     *
     * <pre>{@code
     * E2EEncryption e2ee = E2EEncryption.fromPkcs8Pem(System.getenv("BELLA_BAXTER_PRIVATE_KEY"));
     * }</pre>
     *
     * @param pem PKCS#8 PEM string (with or without the {@code -----BEGIN/END-----} envelope)
     * @throws GeneralSecurityException if the key cannot be parsed or is not a P-256 EC key
     */
    public static E2EEncryption fromPkcs8Pem(String pem) throws GeneralSecurityException {
        String base64 = pem.replaceAll("-----[A-Z ]+-----|\\s", "");
        byte[] der    = Base64.getDecoder().decode(base64);

        KeyFactory kf          = KeyFactory.getInstance("EC");
        PrivateKey privateKey  = kf.generatePrivate(new PKCS8EncodedKeySpec(der));
        PublicKey  publicKey   = extractPublicKeyFromPkcs8Der(der, kf);
        return new E2EEncryption(privateKey, publicKey);
    }

    /**
     * Extracts the embedded P-256 public key from a PKCS#8 EC private key DER blob.
     *
     * <p>PKCS#8 EC keys generated by OpenSSL / {@code bella auth setup} always include
     * the public key as the optional {@code [1]} field inside the inner
     * {@code ECPrivateKey} structure.  We locate the uncompressed point by scanning for
     * the DER BIT-STRING header {@code 03 42 00 04} (BIT STRING, 66-byte content,
     * 0 unused bits, 04 = uncompressed point), then reconstruct a
     * SubjectPublicKeyInfo (SPKI) blob that {@link X509EncodedKeySpec} can consume.
     */
    private static PublicKey extractPublicKeyFromPkcs8Der(byte[] der, KeyFactory kf)
            throws GeneralSecurityException {
        // Scan for the BIT STRING that wraps the uncompressed P-256 public key point.
        // Pattern: 03 42 00 04
        //          ^BIT_STRING  ^length=66  ^no-unused-bits  ^uncompressed-point-indicator
        int pubPointOffset = -1;
        for (int i = 0; i <= der.length - 68; i++) {
            if ((der[i]   & 0xFF) == 0x03
                    && (der[i+1] & 0xFF) == 0x42
                    && (der[i+2] & 0xFF) == 0x00
                    && (der[i+3] & 0xFF) == 0x04) {
                pubPointOffset = i + 3; // point to the 0x04 uncompressed-marker byte
                break;
            }
        }
        if (pubPointOffset == -1 || pubPointOffset + 65 > der.length) {
            throw new GeneralSecurityException(
                    "PKCS#8 key does not contain an embedded P-256 public key. "
                    + "Regenerate the key with: bella auth setup");
        }

        // Build SubjectPublicKeyInfo: fixed P-256 SPKI header (26 bytes) + 04||X||Y (65 bytes)
        byte[] spki = new byte[SPKI_HEADER_P256.length + 65];
        System.arraycopy(SPKI_HEADER_P256, 0, spki, 0,                    SPKI_HEADER_P256.length);
        System.arraycopy(der,  pubPointOffset, spki, SPKI_HEADER_P256.length, 65);

        return kf.generatePublic(new X509EncodedKeySpec(spki));
    }

    /** Decodes a lower-case hex string to bytes (avoids a dependency on HexFormat for JDK 11 compat). */
    private static byte[] hexDecode(String hex) {
        byte[] b = new byte[hex.length() / 2];
        for (int i = 0; i < b.length; i++) {
            b[i] = (byte) Integer.parseInt(hex.substring(2 * i, 2 * i + 2), 16);
        }
        return b;
    }

    /**
     * Base64-encoded SubjectPublicKeyInfo (SPKI) of the client's ephemeral public key.
     * Send this as the value of the {@code X-E2E-Public-Key} request header.
     */
    public String getPublicKeyBase64() {
        return publicKeyBase64;
    }

    /**
     * Decrypt an encrypted secrets payload from the Bella Baxter API.
     *
     * @param responseBodyBytes raw JSON bytes of the API response
     * @return decrypted {@code Map<String, String>} of secrets
     * @throws Exception if decryption fails
     */
    public Map<String, String> decrypt(byte[] responseBodyBytes) throws Exception {
        com.fasterxml.jackson.databind.ObjectMapper mapper =
                new com.fasterxml.jackson.databind.ObjectMapper();
        com.fasterxml.jackson.databind.JsonNode root = mapper.readTree(responseBodyBytes);

        if (!root.path("encrypted").asBoolean(false)) {
            // Plain response — return the secrets map as-is
            Map<String, String> plain = new HashMap<>();
            root.fields().forEachRemaining(e -> {
                if (e.getValue().isTextual()) plain.put(e.getKey(), e.getValue().asText());
            });
            return plain;
        }

        byte[] plaintext = decryptCiphertext(root);

        // Parse JSON → Map<String,String>.
        // Three possible formats returned by the server:
        //   1. Full AllEnvironmentSecretsResponse: {"environmentSlug":..., "secrets":{...}, ...}
        //   2. Array of SecretItem:                [{key:"K", value:"V"}, ...]
        //   3. Legacy flat dict:                   {"K": "V", ...}
        com.fasterxml.jackson.databind.JsonNode secretsNode = mapper.readTree(plaintext);
        Map<String, String> secrets = new HashMap<>();

        if (secretsNode.isObject() && secretsNode.has("secrets")
                && secretsNode.get("secrets").isObject()) {
            // Full AllEnvironmentSecretsResponse — extract nested secrets dict.
            secretsNode.get("secrets").fields()
                    .forEachRemaining(e -> secrets.put(e.getKey(), e.getValue().asText("")));
        } else if (secretsNode.isArray()) {
            // Array of {key, value, ...} items.
            secretsNode.forEach(item -> {
                if (item.has("key")) secrets.put(item.get("key").asText(), item.path("value").asText(""));
            });
        } else {
            // Legacy flat object {KEY: VALUE, ...}.
            secretsNode.fields()
                    .forEachRemaining(e -> secrets.put(e.getKey(), e.getValue().asText()));
        }
        return secrets;
    }

    /**
     * Decrypt the raw plaintext bytes of an encrypted payload.
     *
     * <p>Unlike {@link #decrypt(byte[])} this method returns the full decrypted JSON bytes
     * without any parsing or transformation, so the caller can handle the response shape
     * itself (e.g. to preserve {@code version}, {@code environmentSlug}, etc.)
     *
     * @param responseBodyBytes raw JSON bytes of the {@code E2EEncryptedPayload} response
     * @return raw decrypted plaintext bytes (the original JSON the server encrypted)
     * @throws Exception if decryption fails or the payload is not encrypted
     */
    public byte[] decryptRaw(byte[] responseBodyBytes) throws Exception {
        com.fasterxml.jackson.databind.ObjectMapper mapper =
                new com.fasterxml.jackson.databind.ObjectMapper();
        com.fasterxml.jackson.databind.JsonNode root = mapper.readTree(responseBodyBytes);
        return decryptCiphertext(root);
    }

    /** Core ECDH + HKDF + AES-GCM decryption — returns raw plaintext bytes. */
    private byte[] decryptCiphertext(com.fasterxml.jackson.databind.JsonNode root) throws Exception {
        byte[] serverPubBytes = Base64.getDecoder().decode(root.get("serverPublicKey").asText());
        byte[] nonce          = Base64.getDecoder().decode(root.get("nonce").asText());
        byte[] tag            = Base64.getDecoder().decode(root.get("tag").asText());
        byte[] ciphertext     = Base64.getDecoder().decode(root.get("ciphertext").asText());

        // 1. Import server ephemeral public key (SPKI / X.509 DER)
        KeyFactory kf = KeyFactory.getInstance("EC");
        PublicKey serverPub = kf.generatePublic(new X509EncodedKeySpec(serverPubBytes));

        // 2. ECDH → raw shared secret
        KeyAgreement ka = KeyAgreement.getInstance("ECDH");
        ka.init(privateKey);
        ka.doPhase(serverPub, true);
        byte[] sharedSecret = ka.generateSecret();

        // 3. HKDF-SHA256 → 32-byte AES key  (salt = 32 zeros per RFC 5869 §2.2)
        byte[] aesKey = hkdfSHA256(sharedSecret, HKDF_INFO.getBytes("UTF-8"));

        // 4. AES-256-GCM decrypt
        SecretKeySpec keySpec = new SecretKeySpec(aesKey, "AES");
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, keySpec, new GCMParameterSpec(128, nonce));
        // Java AES/GCM/NoPadding expects ciphertext + tag concatenated.
        byte[] combined = new byte[ciphertext.length + tag.length];
        System.arraycopy(ciphertext, 0, combined, 0,                ciphertext.length);
        System.arraycopy(tag,        0, combined, ciphertext.length, tag.length);

        return cipher.doFinal(combined);
    }

    // ── HKDF-SHA256 (RFC 5869) ─────────────────────────────────────────────────

    /**
     * Derives a 32-byte key using HKDF-SHA256 with a zero salt.
     *
     * <p>Matches .NET {@code HKDF.DeriveKey(HashAlgorithmName.SHA256, ikm,
     * outputLength: 32, salt: null, info: info)}.
     */
    private static byte[] hkdfSHA256(byte[] ikm, byte[] info) throws Exception {
        // Extract: PRK = HMAC-SHA256(salt = zeros[32], IKM)
        byte[] salt = new byte[32]; // SHA-256 hash length
        Mac mac = Mac.getInstance("HmacSHA256");
        mac.init(new SecretKeySpec(salt, "HmacSHA256"));
        byte[] prk = mac.doFinal(ikm);

        // Expand: T(1) = HMAC-SHA256(PRK, info || 0x01)  — 32 bytes = 1 block
        mac.init(new SecretKeySpec(prk, "HmacSHA256"));
        mac.update(info);
        mac.update((byte) 0x01);
        return mac.doFinal(); // 32 bytes
    }
}
